# Generated by Django 2.2 on 2020-10-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201004_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
