# Generated by Django 2.2 on 2020-10-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='book1', on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
            preserve_default=False,
        ),
    ]
