# Generated by Django 2.2 on 2020-10-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_cartdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartDetails',
        ),
    ]
