# Generated by Django 2.2 on 2020-10-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='website.Product', to_field='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, unique=True, upload_to='images/'),
        ),
    ]
