# Generated by Django 2.2 on 2020-10-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201015_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
    ]
