# Generated by Django 2.2 on 2020-10-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='website.Product', to_field='image'),
        ),
    ]
