# Generated by Django 2.2 on 2020-10-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_cartdetails_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='img',
        ),
    ]
